import Head from "next/head";
import Image from "next/image";
import Card from "../components/Card";
import Banner from "../components/Banner";

import { useContext, useEffect, useState } from "react";
import { useTrackLocation } from "../hooks/useTrackLocation";

import { fetchCoffeeStores } from "../lib/coffee-stores";
import { StoreContext } from "../store/coffeeStores.context";
import ACTION_TYPES from "../store/coffeeStores.types";
import styles from "../styles/Home.module.css";

// data will be stored in a CDN after the build process
export async function getStaticProps() {
  const coffeeStores = await fetchCoffeeStores(
    "33.893582981652145%2C35.47158364033414"
  );
  return {
    // passed as props to this page FC
    props: { coffeeStores },
  };
}

export default function Home({ coffeeStores }) {
  const { handleTrackLocation, locationErrorMsg, isLoading } =
    useTrackLocation();

  /**
   * When current location changes (clicking on View Nearby button)
   * new stores will be fetched and published to the page
   */
  const { state, dispatch } = useContext(StoreContext);
  const [coffeeStoreError, setCoffeeStoreError] = useState(null);

  useEffect(() => {
    console.log("running once on load");
    async function fetchNearbyStores() {
      try {
        const coffeeStores = await fetchCoffeeStores(state.coords);

        if (coffeeStores.length) {
          console.log("running twice on load");
          dispatch({
            type: ACTION_TYPES.SET_COFFEE_STORES,
            payload: coffeeStores,
          });
        }
        return coffeeStores;
      } catch (error) {
        setCoffeeStoreError(error.message);
        console.log(error);
      }
    }
    fetchNearbyStores();
  }, [state.coords]);

  const clickHandler = () => {
    handleTrackLocation();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={isLoading ? "Locating..." : "View stores nearby"}
          clickHandler={clickHandler}
        />
        {locationErrorMsg && <p>Something went wrong: {locationErrorMsg}</p>}
        {coffeeStoreError && <p>Something went wrong: {coffeeStoreError}</p>}
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>

        {state.coffeeStores.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Stores Near Me</h2>
            <div className={styles.cardLayout}>
              {state.coffeeStores.map(
                ({ fsq_id, name, description, imgUrl }) => {
                  return (
                    <Card
                      key={fsq_id}
                      name={name}
                      description={description}
                      imgUrl={imgUrl}
                      href={`/coffee-store/${fsq_id}`}
                      className={styles.card}
                    />
                  );
                }
              )}
            </div>
          </div>
        )}

        {coffeeStores.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Beirut Stores</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map(({ fsq_id, name, description, imgUrl }) => {
                return (
                  <Card
                    key={fsq_id}
                    name={name}
                    description={description}
                    imgUrl={imgUrl}
                    href={`/coffee-store/${fsq_id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </div>
        )}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
