import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Card from "../components/Card";
import styles from "../styles/Home.module.css";

import coffeeStoresData from "../data/coffee-stores.json";

// data will be stored in a CDN after the build process
export async function getStaticProps() {
  // code in this function runs in the server only (safe)
  return {
    // passed as props to this page FC
    props: { coffeeStores: coffeeStoresData },
  };
}

export default function Home({ coffeeStores }) {
  const clickHandler = () => {
    console.log({ coffeeStores });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" clickHandler={clickHandler} />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>
        {coffeeStores.length && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map(({ name, imgUrl, id }) => {
                return (
                  <Card
                    key={id}
                    name={name}
                    imgUrl={imgUrl}
                    href={`/coffee-store/${id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
